version: 5.0.0.{build}-beta
branches:
  only:
  - develop
configuration: release
platform: Any CPU
init:
- ps: >-
    Update-AppveyorBuild -Version "5.0.0.$env:appveyor_build_number-$(Get-Date -format yyyyMMdd)-$env:appveyor_repo_branch"

    Write-Host "5.0.0.$env:appveyor_build_number-$(Get-Date -format yyyyMMdd)-$env:appveyor_repo_branch"
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  assembly_version: 5.0.0.{build}
  file_version: 5.0.0.{build}
nuget:
  project_feed: true
before_build:
- cmd: dotnet restore ./src/EPPlus.sln
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: EPPlus Nuget Package